backend: # The two following lines need to be indented
  name: git-gateway # The authentication method we use for Netlify CMS
  branch: main # Branch to update when we push our content (it can be any branch in our repo)

# Do not indent these lines
media_folder: "public/images/uploads" # Exact path where we store the uploaded media
public_folder: "/images/uploads" # We do not need to specify the /public part as all the files from it are stored in the root directory after the build step

logo_url: /images/logo/logo.png
